### ISSUE TITLE
Conflict with Ender IO

### ISSUE THREAD

**Issue by CloWnicide** [the-realest-stu/Thaumic-Periphery#6]
Seems to be an issue upon loading the game while having TP and Ender IO installed.

Minecraft Version: 1.12.2
Forge Version: 14.23.4.2712
Mod Version: 0.2.4

Crash report:

<details>
<summary> Click to expand </summary>
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b150.jar)
  LibLoader (# LibLoader.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.31.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
  RandomPatches (randompatches-1.12.2-1.1.0.0.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  FMLPlugin (elulib-0.1.12.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  EECore (ExpandedEquivalence-1.12.2-4r.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  CoreMod (TickProfiler-1.12-0.0.4.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  llibrary (llibrary-core-1.0.6-1.12.2.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  SHLoadingPlugin (ScalingHealth-1.12-1.3.16-99.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.9.jar)
  AstralCore (astralsorcery-1.12.2-1.9.1.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  Plugin (NotEnoughIDs-1.5.4.2.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.1.9.jar)
  Wizardry Plugin (wizardry-0.8.5.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.4.0-80.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  HCASM (HammerCore-1.12.2-2.0.0.2.jar)
  DCLoadingPlugin (DummyCoreUnofficial-2.4.112.3.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.8-core.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 7/6/18 10:26 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thaumic Periphery (thaumicperiphery)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: -1
	at java.util.AbstractList.rangeCheckForAdd(AbstractList.java:605)
	at java.util.AbstractList.listIterator(AbstractList.java:325)
	at java.util.AbstractList.removeRange(AbstractList.java:568)
	at java.util.AbstractList.clear(AbstractList.java:234)
	at net.minecraft.util.NonNullList.clear(SourceFile:74)
	at com.enderio.core.common.util.stackable.Things.getItemStacksRaw(Things.java:335)
	at com.enderio.core.common.util.stackable.Things.isValid(Things.java:300)
	at com.enderio.core.common.util.stackable.Things.isPotentiallyValid(Things.java:304)
	at crazypants.enderio.base.config.recipes.ShapedRecipe.func_77571_b(ShapedRecipe.java:40)
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromCraftingRecipes(ThaumcraftCraftingManager.java:467)
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromRecipes(ThaumcraftCraftingManager.java:567)
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:389)
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:355)
	at thaumcraft.common.lib.InternalMethodHandler.generateTags(InternalMethodHandler.java:91)
	at thaumcraft.api.aspects.AspectHelper.generateTags(AspectHelper.java:73)
	at thaumcraft.api.ThaumcraftApi.registerComplexObjectTag(ThaumcraftApi.java:337)
	at thaumicperiphery.proxy.CommonProxy.initAspects(CommonProxy.java:130)
	at thaumicperiphery.proxy.CommonProxy.postInit(CommonProxy.java:73)
	at thaumicperiphery.proxy.ClientProxy.postInit(ClientProxy.java:46)
	at thaumicperiphery.ThaumicPeriphery.postInit(ThaumicPeriphery.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:626)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:329)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
</details>

**Comment by LemADEC** [comment]
Crash report is incomplete. Use gist or something similar to share full report

**Comment by the-realest-stu** [comment]
It would also be helpful to know the versions of Thaumcraft and EnderIO you have installed.
